---
#-----------------------------------------
# Setup necessary kernel parameters
#-----------------------------------------
- name: setup necessary kernel prameters
  become: yes
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value}}"
    state: present
    reload: no
  with_items: "{{ kernel_params }}"